In [1]:
# Description: This program detects if an eamil is sapam(1) or not (0)

In [ ]:
# Import liabraries


import numpy as np
import pandas as pd
import nltk         # nltk --> Natural Language Tool Kit
from nltk.corpus import stopwords
import string

In [2]:
# loading dataset

df = pd.read_csv('F:/M.Sc/Applied Machine Learning/emails.csv')

In [4]:
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
# print the shape(Get the number of rows & columns)
df.shape

(5728, 2)

In [6]:
# Get the columns names
df.columns

Index(['text', 'spam'], dtype='object')

In [10]:
# Check for duplicates adn remove them
df.drop_duplicates(inplace = True)


In [11]:
# Show the new shape (number of rows and columns)
df.shape

(5695, 2)

In [13]:
# Show the number of missing(NAN, NaN, na) data for each column

df.isnull().sum()

text    0
spam    0
dtype: int64

In [16]:
# Download the stopwords package

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [40]:
def process_text(text):
    # 1 Remove punctuation
    # 2 remove stopwords
    # 3 return a list of clean text words
    
    #1
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    #2
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #3
    return clean_words

In [41]:
# Show the tokenization (a list of tokens also called lemas)

df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [44]:
# Example 

message4 = 'hello world hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()





# Convert the text to a matrix of token counts

from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)

        #description of output:
          # first 3 rows says about messagge4's output
            # here firs row in the output says that there are 3 words simllar here[they are hello word 3 times]
            # 2nd row says one word 2 times here[world]
            # 3rd row says 1 word similar [play 1 time]

          # last 3 rows says about messagge5's output
            # 4th row says it has 1 simillar word [one appears 1 time]
            # 5th row says it has 4 similar word [test appears 4 tims]
            # 6th row says it has 1 similar word [hello]

    
    
    
print(bow4.shape)
        # output:  (2, 5)
        # output says there are 2 rows[message4,message5] 
        # & 5 uniques word [hello, world, play, test, one]

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1
(2, 5)


In [46]:
# Convert a collection of text to a matrix of tokens

from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])

In [49]:
# Split teh data into 80% training & 20% testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size=0.20, random_state = 0)

In [50]:
# Get the shape of messages_bow

messages_bow.shape

(5695, 37229)

In [51]:
# Create and train the Naive Bayes Classifier

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [53]:
# Print the predictions

print(classifier.predict(X_train))
    # Here in output, first 3 values are first 3 row's value and last 3 values are last 3 rows
    

# Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [57]:
# Evalute the model on the training data set

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy:', accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3445   12]
 [   1 1098]]

Accuracy: 0.9971466198419666


In [58]:
# Print the predictions

print(classifier.predict(X_test))
    # Here in output, first 3 values are first 3 row's value and last 3 values are last 3 rows
    

# Print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [61]:
# Evalute the model on the test data set

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy:', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]

Accuracy: 0.9920983318700615
